"""Add role field to User model

Revision ID: b3bbfdf42a2f
Revises: c84e2eb90ec6
Create Date: 2025-03-01 22:27:54.601518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3bbfdf42a2f'
down_revision = 'c84e2eb90ec6'
branch_labels = None
depends_on = None


def upgrade():
   # Step 1: Add the role column as nullable
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=True))

    # Step 2: Update existing records to set a default value
    op.execute("UPDATE users SET role = 'owner' WHERE role IS NULL")

    # Step 3: Alter the column to be non-nullable
    op.alter_column('users', 'role', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
