name: HMrecord

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd ~/HMRecord
        git pull origin main
        git status
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

   
    - name: Restart Gunicorn
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd ~/HMRecord
          source venv/bin/activate
          pkill gunicorn
          gunicorn -c gunicorn_config.py app:app
